# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/website"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
